Parameter parsing
sqlectron/sql-query-identifier pull request #40
Opened 2021-07-23 22:01 UTC by rathboma

This wasn't actually very hard honestly.

Fix #39 

@MasterOdin let me know what you think. This doesn't actually break the v2 API, just adds a new field.

2021-07-24 00:16 UTC, MasterOdin requested changes

2021-07-24 00:16 UTC, MasterOdin commented on .gitignore
> -yarn.lock
I am of the opinion to ignore lock files for library packages as bumping lockfile versions isn't super useful. We also probably want to (ideally) set up the CI to test on the lowest support versions of packages as well as highest, which a lockfile would just get in the way of.

2021-07-24 00:16 UTC, MasterOdin commented on src/defines.ts
> +  parameters?: string[];
I think I'd prefer just making this a permanent field to the result. Easier to deal with on the consumer code, and I don't consider adding an additional field to the return result a breaking change.

2021-07-24 00:16 UTC, MasterOdin commented on src/parser.ts
> +        statement.parameters ||= []
Just want to confirm that typescript compiles this down to something that isn't logical or as that's not supported on Node < 15, though again, totally fine (and would prefer) just making it part of `INITIAL_STATEMENT` and always be there for simplicity.

2021-07-24 00:16 UTC, MasterOdin commented on test/tokenizer/index.spec.ts
> +  })
Can you add more tests around the different dialects here?

2021-07-24 00:18 UTC, MasterOdin commented
Yeah, the limitation is centered around the fact that we aren't implementing a true AST parser here. I have plans to work on a general (with dialect support) SQL AST parser in JS, just haven't found the time yet to do it, which would certainly be a v3 or v4 addition to be more precise in parsing.

2021-08-25 06:47 UTC, MasterOdin approved these changes

2021-08-25 13:25 UTC, merged

2021-08-30 02:16 UTC, rathboma commented
Thanks for doing the extra work on this! Been a crazy few weeks.